version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./db/sakila-schema.sql:/docker-entrypoint-initdb.d/a.sql
      - ./db/sakila-data.sql:/docker-entrypoint-initdb.d/b.sql
    ports:
      - 3306:3306
